services:
  db:
    image: postgres:17.2
    container_name: wallet_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mydifficultnewpassword
      POSTGRES_DB: wallet_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet_service
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mydifficultnewpassword
      - DB_NAME=wallet_db
    ports:
      - "8080:8080"
    volumes:
      - .:/app       
    depends_on:
      - db    
    command: go run main.go 

volumes:
  db_data:
  go_cache:
